"""Seed menu data for local testing. No database required — in-memory only."""

SAMPLE_MENU: list[dict] = [  # type: ignore[type-arg]
    {
        "id": "1",
        "name": "Grilled Chicken Bowl",
        "description": "Marinated chicken with jasmine rice, pickled vegetables, and sweet chili sauce",
        "price_usd": 18.50,
        "category": "healthy",
        "cuisine": "thai",
        "calories": 450,
        "allergens": ["soy"],
        "active": True,
    },
    {
        "id": "2",
        "name": "Pasta Carbonara",
        "description": "Classic Roman pasta with guanciale, egg, pecorino, and black pepper",
        "price_usd": 22.00,
        "category": "comfort",
        "cuisine": "italian",
        "calories": 750,
        "allergens": ["dairy", "eggs", "gluten"],
        "active": True,
    },
    {
        "id": "3",
        "name": "Shrimp Tacos",
        "description": "Crispy shrimp with mango salsa, avocado crema, and corn tortillas",
        "price_usd": 15.00,
        "category": "light",
        "cuisine": "mexican",
        "calories": 380,
        "allergens": ["shellfish"],
        "active": True,
    },
    {
        "id": "4",
        "name": "Tofu Stir Fry",
        "description": "Crispy tofu with bok choy, mushrooms, and ginger-garlic sauce over brown rice",
        "price_usd": 14.00,
        "category": "healthy",
        "cuisine": "thai",
        "calories": 350,
        "allergens": ["soy"],
        "active": True,
    },
    {
        "id": "5",
        "name": "Caesar Salad",
        "description": "Romaine lettuce, parmesan, croutons, and house-made Caesar dressing",
        "price_usd": 12.50,
        "category": "light",
        "cuisine": "italian",
        "calories": 320,
        "allergens": ["dairy", "gluten", "eggs"],
        "active": True,
    },
    {
        "id": "6",
        "name": "BBQ Pulled Pork Sandwich",
        "description": "Slow-smoked pork with coleslaw and pickles on a brioche bun",
        "price_usd": 16.00,
        "category": "comfort",
        "cuisine": "american",
        "calories": 680,
        "allergens": ["gluten"],
        "active": True,
    },
    {
        "id": "7",
        "name": "Salmon Poke Bowl",
        "description": "Fresh salmon, edamame, avocado, seaweed, and ponzu over sushi rice",
        "price_usd": 24.00,
        "category": "healthy",
        "cuisine": "japanese",
        "calories": 520,
        "allergens": ["fish", "soy"],
        "active": True,
    },
    {
        "id": "8",
        "name": "Veggie Burrito",
        "description": "Black beans, rice, roasted peppers, guacamole, and salsa in a flour tortilla",
        "price_usd": 13.50,
        "category": "comfort",
        "cuisine": "mexican",
        "calories": 580,
        "allergens": ["gluten"],
        "active": True,
    },
    {
        "id": "9",
        "name": "Chicken Tikka Masala",
        "description": "Tender chicken in creamy tomato-spice sauce with basmati rice and naan",
        "price_usd": 19.00,
        "category": "comfort",
        "cuisine": "indian",
        "calories": 650,
        "allergens": ["dairy", "gluten"],
        "active": True,
    },
    {
        "id": "10",
        "name": "Mediterranean Grain Bowl",
        "description": "Falafel, hummus, tabbouleh, roasted vegetables, and tahini over quinoa",
        "price_usd": 16.50,
        "category": "healthy",
        "cuisine": "mediterranean",
        "calories": 480,
        "allergens": ["sesame", "gluten"],
        "active": True,
    },
    # --- Added variety below ---
    {
        "id": "11",
        "name": "Margherita Pizza",
        "description": "Wood-fired pizza with tomato, mozzarella, basil, and olive oil",
        "price_usd": 17.00,
        "category": "comfort",
        "cuisine": "italian",
        "calories": 700,
        "allergens": ["dairy", "gluten"],
        "active": True,
    },
    {
        "id": "12",
        "name": "Beef Shawarma Wrap",
        "description": "Spiced beef with garlic sauce, pickles, and fries wrapped in flatbread",
        "price_usd": 14.50,
        "category": "comfort",
        "cuisine": "middle eastern",
        "calories": 620,
        "allergens": ["gluten", "dairy"],
        "active": True,
    },
    {
        "id": "13",
        "name": "Greek Salad",
        "description": "Tomatoes, cucumber, olives, feta cheese, and oregano dressing",
        "price_usd": 13.00,
        "category": "light",
        "cuisine": "mediterranean",
        "calories": 280,
        "allergens": ["dairy"],
        "active": True,
    },
    {
        "id": "14",
        "name": "Butter Chicken",
        "description": "Creamy tomato curry with tender chicken and fragrant spices",
        "price_usd": 20.00,
        "category": "comfort",
        "cuisine": "indian",
        "calories": 720,
        "allergens": ["dairy"],
        "active": True,
    },
    {
        "id": "15",
        "name": "Sushi Platter",
        "description": "Assorted nigiri and maki rolls with fresh fish and vegetables",
        "price_usd": 28.00,
        "category": "light",
        "cuisine": "japanese",
        "calories": 500,
        "allergens": ["fish", "soy"],
        "active": True,
    },
    {
        "id": "16",
        "name": "Cheeseburger Deluxe",
        "description": "Grilled beef patty with cheddar, lettuce, tomato, and fries",
        "price_usd": 18.00,
        "category": "comfort",
        "cuisine": "american",
        "calories": 850,
        "allergens": ["dairy", "gluten"],
        "active": True,
    },
    {
        "id": "17",
        "name": "Pad Thai",
        "description": "Rice noodles stir-fried with shrimp, peanuts, egg, and tamarind sauce",
        "price_usd": 17.50,
        "category": "comfort",
        "cuisine": "thai",
        "calories": 600,
        "allergens": ["peanuts", "shellfish", "eggs"],
        "active": True,
    },
    {
        "id": "18",
        "name": "Vegan Buddha Bowl",
        "description": "Chickpeas, roasted sweet potatoes, kale, avocado, and tahini dressing",
        "price_usd": 15.50,
        "category": "healthy",
        "cuisine": "fusion",
        "calories": 420,
        "allergens": ["sesame"],
        "active": True,
    },
    {
        "id": "19",
        "name": "Ramen Noodle Soup",
        "description": "Rich pork broth with noodles, soft egg, chashu, and scallions",
        "price_usd": 19.50,
        "category": "comfort",
        "cuisine": "japanese",
        "calories": 700,
        "allergens": ["gluten", "eggs", "soy"],
        "active": True,
    },
    {
        "id": "20",
        "name": "Falafel Wrap",
        "description": "Crispy falafel with tahini, vegetables, and pita bread",
        "price_usd": 12.50,
        "category": "light",
        "cuisine": "middle eastern",
        "calories": 450,
        "allergens": ["gluten", "sesame"],
        "active": True,
    },
    {
        "id": "21",
        "name": "Steak Frites",
        "description": "Grilled steak with herb butter and crispy french fries",
        "price_usd": 26.00,
        "category": "comfort",
        "cuisine": "french",
        "calories": 900,
        "allergens": ["dairy"],
        "active": True,
    },
    {
        "id": "22",
        "name": "Chicken Caesar Wrap",
        "description": "Grilled chicken, romaine, parmesan, and Caesar dressing in a wrap",
        "price_usd": 13.50,
        "category": "light",
        "cuisine": "american",
        "calories": 520,
        "allergens": ["dairy", "gluten", "eggs"],
        "active": True,
    },
    {
        "id": "23",
        "name": "Dim Sum Basket",
        "description": "Assorted dumplings including shrimp, pork, and vegetable fillings",
        "price_usd": 18.50,
        "category": "light",
        "cuisine": "chinese",
        "calories": 400,
        "allergens": ["shellfish", "gluten"],
        "active": True,
    },
    {
        "id": "24",
        "name": "Eggplant Parmesan",
        "description": "Breaded eggplant baked with tomato sauce and melted cheese",
        "price_usd": 16.50,
        "category": "comfort",
        "cuisine": "italian",
        "calories": 650,
        "allergens": ["dairy", "gluten"],
        "active": True,
    },
    {
        "id": "25",
        "name": "Lentil Soup",
        "description": "Hearty lentil soup with vegetables and spices",
        "price_usd": 11.00,
        "category": "healthy",
        "cuisine": "mediterranean",
        "calories": 300,
        "allergens": [],
        "active": True,
    },
]
