"""Seed menu data for local testing. No database required — in-memory only."""

SAMPLE_MENU: list[dict] = [  # type: ignore[type-arg]
    {
        "id": "1",
        "name": "Grilled Chicken Bowl",
        "description": "Marinated chicken with jasmine rice, pickled vegetables, and sweet chili sauce",
        "price_usd": 18.50,
        "category": "healthy",
        "cuisine": "thai",
        "calories": 450,
        "allergens": ["soy"],
        "active": True,
    },
    {
        "id": "2",
        "name": "Pasta Carbonara",
        "description": "Classic Roman pasta with guanciale, egg, pecorino, and black pepper",
        "price_usd": 22.00,
        "category": "comfort",
        "cuisine": "italian",
        "calories": 750,
        "allergens": ["dairy", "eggs", "gluten"],
        "active": True,
    },
    {
        "id": "3",
        "name": "Shrimp Tacos",
        "description": "Crispy shrimp with mango salsa, avocado crema, and corn tortillas",
        "price_usd": 15.00,
        "category": "light",
        "cuisine": "mexican",
        "calories": 380,
        "allergens": ["shellfish"],
        "active": True,
    },
    {
        "id": "4",
        "name": "Tofu Stir Fry",
        "description": "Crispy tofu with bok choy, mushrooms, and ginger-garlic sauce over brown rice",
        "price_usd": 14.00,
        "category": "healthy",
        "cuisine": "thai",
        "calories": 350,
        "allergens": ["soy"],
        "active": True,
    },
    {
        "id": "5",
        "name": "Caesar Salad",
        "description": "Romaine lettuce, parmesan, croutons, and house-made Caesar dressing",
        "price_usd": 12.50,
        "category": "light",
        "cuisine": "italian",
        "calories": 320,
        "allergens": ["dairy", "gluten", "eggs"],
        "active": True,
    },
    {
        "id": "6",
        "name": "BBQ Pulled Pork Sandwich",
        "description": "Slow-smoked pork with coleslaw and pickles on a brioche bun",
        "price_usd": 16.00,
        "category": "comfort",
        "cuisine": "american",
        "calories": 680,
        "allergens": ["gluten"],
        "active": True,
    },
    {
        "id": "7",
        "name": "Salmon Poke Bowl",
        "description": "Fresh salmon, edamame, avocado, seaweed, and ponzu over sushi rice",
        "price_usd": 24.00,
        "category": "healthy",
        "cuisine": "japanese",
        "calories": 520,
        "allergens": ["fish", "soy"],
        "active": True,
    },
    {
        "id": "8",
        "name": "Veggie Burrito",
        "description": "Black beans, rice, roasted peppers, guacamole, and salsa in a flour tortilla",
        "price_usd": 13.50,
        "category": "comfort",
        "cuisine": "mexican",
        "calories": 580,
        "allergens": ["gluten"],
        "active": True,
    },
    {
        "id": "9",
        "name": "Chicken Tikka Masala",
        "description": "Tender chicken in creamy tomato-spice sauce with basmati rice and naan",
        "price_usd": 19.00,
        "category": "comfort",
        "cuisine": "indian",
        "calories": 650,
        "allergens": ["dairy", "gluten"],
        "active": True,
    },
    {
        "id": "10",
        "name": "Mediterranean Grain Bowl",
        "description": "Falafel, hummus, tabbouleh, roasted vegetables, and tahini over quinoa",
        "price_usd": 16.50,
        "category": "healthy",
        "cuisine": "mediterranean",
        "calories": 480,
        "allergens": ["sesame", "gluten"],
        "active": True,
    },
]
