"""initial schema with audit_trail

Revision ID: 0256d88cc301
Revises: 
Create Date: 2026-04-07 09:11:31.276688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0256d88cc301'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trace_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('decision_type', sa.Enum('RECOMMENDATION', 'ALLERGY_FILTER', 'POLICY_CHECK', 'APPROVAL_ROUTE', 'ORDER_SUBMIT', name='decisiontype'), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('ACCEPTED', 'REJECTED', 'OVERRIDDEN', 'PENDING', name='auditoutcome'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_trace_id'), 'audit_trail', ['trace_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('ORDER_PLACED', 'ITEM_ADDED', 'ITEM_REMOVED', 'ITEM_SWAPPED', 'SUGGESTION_ACCEPTED', 'SUGGESTION_REJECTED', 'RATING_GIVEN', 'MEALPLAN_EDITED', 'ALLERGY_DECLARED', name='eventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('cuisine', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Time(), nullable=True),
    sa.Column('available_to', sa.Time(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'SUBMITTED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('BUDGET_CAP', 'PER_PERSON_LIMIT', 'APPROVAL_THRESHOLD', 'RESTRICTED_ITEMS', name='policyruletype'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_department_id'), 'policies', ['department_id'], unique=False)
    op.create_table('menu_item_ingredients',
    sa.Column('menu_item_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('is_allergen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('menu_item_id', 'ingredient_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('menu_item_ingredients')
    op.drop_index(op.f('ix_policies_department_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('menu_items')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_trail_trace_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
